openapi: 3.0.1
info:
  title: HAPI FHIR Server
  contact: {}
  version: 6.0.0
servers:
- url: http://localhost:8080/
  description: HAPI FHIR Server
tags:
- name: System Level Operations
  description: Server-level operations
- name: Encounter
  description: The Encounter FHIR resource type
- name: OperationDefinition
  description: The OperationDefinition FHIR resource type
- name: Patient
  description: The Patient FHIR resource type
paths:
  /metadata:
    get:
      tags:
      - System Level Operations
      summary: "server-capabilities: Fetch the server FHIR CapabilityStatement"
      responses:
        "200":
          description: Success
          content:
            application/fhir+json:
              schema:
                $ref: '#/components/schemas/FHIR-JSON-RESOURCE'
              example: "{\n  \"resourceType\": \"CapabilityStatement\"\n}"
            application/fhir+xml:
              schema:
                $ref: '#/components/schemas/FHIR-XML-RESOURCE'
              example: <CapabilityStatement xmlns="http://hl7.org/fhir"></CapabilityStatement>
  /$process-message:
    post:
      tags:
      - System Level Operations
      requestBody:
        content:
          application/fhir+json:
            schema:
              title: FHIR Resource
              type: object
            example: "{\n  \"resourceType\": \"Parameters\"\n}"
      responses:
        "200":
          description: Success
          content:
            application/fhir+json:
              schema:
                $ref: '#/components/schemas/FHIR-JSON-RESOURCE'
            application/fhir+xml:
              schema:
                $ref: '#/components/schemas/FHIR-XML-RESOURCE'
  /Encounter/{id}:
    get:
      tags:
      - Encounter
      summary: "read-instance: Read Encounter instance"
      parameters:
      - name: id
        in: path
        description: The resource ID
        required: true
        style: simple
        schema:
          minimum: 1
          type: string
        example: "123"
      responses:
        "200":
          description: Success
          content:
            application/fhir+json:
              schema:
                $ref: '#/components/schemas/FHIR-JSON-RESOURCE'
            application/fhir+xml:
              schema:
                $ref: '#/components/schemas/FHIR-XML-RESOURCE'
  /Encounter/{id}/_history/{version_id}:
    get:
      tags:
      - Encounter
      summary: "vread-instance: Read Encounter instance with specific version"
      parameters:
      - name: id
        in: path
        description: The resource ID
        required: true
        style: simple
        schema:
          minimum: 1
          type: string
        example: "123"
      - name: version_id
        in: path
        description: The resource version ID
        required: true
        style: simple
        schema:
          minimum: 1
          type: string
        example: "1"
      responses:
        "200":
          description: Success
          content:
            application/fhir+json:
              schema:
                $ref: '#/components/schemas/FHIR-JSON-RESOURCE'
            application/fhir+xml:
              schema:
                $ref: '#/components/schemas/FHIR-XML-RESOURCE'
  /OperationDefinition/{id}:
    get:
      tags:
      - OperationDefinition
      summary: "read-instance: Read OperationDefinition instance"
      parameters:
      - name: id
        in: path
        description: The resource ID
        required: true
        style: simple
        schema:
          minimum: 1
          type: string
        example: "123"
      responses:
        "200":
          description: Success
          content:
            application/fhir+json:
              schema:
                $ref: '#/components/schemas/FHIR-JSON-RESOURCE'
            application/fhir+xml:
              schema:
                $ref: '#/components/schemas/FHIR-XML-RESOURCE'
  /Patient/{id}:
    get:
      tags:
      - Patient
      summary: "read-instance: Read Patient instance"
      parameters:
      - name: id
        in: path
        description: The resource ID
        required: true
        style: simple
        schema:
          minimum: 1
          type: string
        example: "123"
      responses:
        "200":
          description: Success
          content:
            application/fhir+json:
              schema:
                $ref: '#/components/schemas/FHIR-JSON-RESOURCE'
            application/fhir+xml:
              schema:
                $ref: '#/components/schemas/FHIR-XML-RESOURCE'
  /Patient/{id}/_history/{version_id}:
    get:
      tags:
      - Patient
      summary: "vread-instance: Read Patient instance with specific version"
      parameters:
      - name: id
        in: path
        description: The resource ID
        required: true
        style: simple
        schema:
          minimum: 1
          type: string
        example: "123"
      - name: version_id
        in: path
        description: The resource version ID
        required: true
        style: simple
        schema:
          minimum: 1
          type: string
        example: "1"
      responses:
        "200":
          description: Success
          content:
            application/fhir+json:
              schema:
                $ref: '#/components/schemas/FHIR-JSON-RESOURCE'
            application/fhir+xml:
              schema:
                $ref: '#/components/schemas/FHIR-XML-RESOURCE'
components:
  schemas:
    FHIR-JSON-RESOURCE:
      type: object
      description: A FHIR resource
    FHIR-XML-RESOURCE:
      type: object
      description: A FHIR resource
